GATEWAY: http://192.168.1.119:8086/fjs

security:
    oauth2:
        resource:
            id: ${eureka.instance.instanceId}
            token-info-uri: ${GATEWAY}/apollo/oauth/check_token
            user-info-uri: ${GATEWAY}/apollo/user
        client:
            user-authorization-uri: ${GATEWAY}/apollo/oauth/authorize
            access-token-uri: ${GATEWAY}/apollo/oauth/token
            authentication-scheme: query
            client-authentication-scheme: form
            client-id: cronus
            client-secret: 123456
            grant-type: authorization_code
            scope: app
            use-current-uri: false
            #pre-established-redirect-uri: http://localhost:8082
    basic:
        enabled: false

base:
    key: 356o192c191db04c54513b0lc28d46ee63954iab
    url: http://beta-base.fang-crm.com/Api/App/
    url.document: http://beta-sale.fang-crm.com/Api/Document/
eureka:
    client:
        serviceUrl:
            defaultZone: http://user:user@192.168.1.119:8087/eureka/
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        prefer-ip-address: true
        instanceId: ${spring.cloud.client.ipAddress}:${server.port}
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 10
feign:
    compression:
        request:
            enabled: true
            mime-types: text/xml,application/xml,application/json
            min-request-size: 2048
        response:
            enabled: true
    hystrix:
        enabled: false
logging:
    file: ./log/cronus.log
    level:
        project:
            user:
                UserClient: DEBUG
sale:
    key: 356a192b7913b06c54574d18c28d46e6395428ab
    url: http://beta-sale.fang-crm.com/Api/App/
server:
    port: 8099
spring:
    application:
        name: cronus0418
