version: '3.1'
services:
  cronuscrm0502:
    image: 192.168.1.126/library/fjs/cronuscrm0502:branch1
    deploy:
      replicas: 1
      update_config: 
        parallelism: 1   
        delay: 2s        
      resources:
        limits:
          cpus: "0.5"
          memory: 2000M
      restart_policy:
        condition: on-failure
    networks:
      fjs_overlay_branch1:
        aliases:
          - cronuscrm0502
    ports:
      - "1281:8220"
    environment:
      - CONFIG_PROFILE=sitcrm0502
      - CONFIG_PASSWORD=123456
      - CONFIG_SERVER_ADDRESS=zues
      - CONFIG_SERVER_PORT=6020
      - EUREKA_PASSWORD=123456
    command:
      - java 
      - '-Duser.timezone=Asia/Shanghai'
      - '-Dfile.encoding=UTF8'
      - '-Djava.security.egd=file:/dev/./urandom'
      - '-server'
      - '-Xmx2000M'
      - '-XX:+UseParallelGC'
      - '-jar'
      - /opt/branch1-cronuscrm0502-1.0.0.war
networks:
  fjs_overlay_branch1:
    external:
      name: fjs_overlay_branch1
